### ISSUE TITLE
Plugin not working.

### ISSUE THREAD

**Issue by BSpawns** [AnkouOSRS/crab-stun-timers#5]
Not sure why but after last client update the plugin has stopped working and no longer displays the timer on stuns for crabs. I have tried removing it and disabling and re-enabling it. Does it have conflicts with "Cox Additions" plugin?.

**Comment by AnkouOSRS** [comment]
It was indeed the last game update that broke it, not some plugin conflict.
I'll look into fixing it when I get a chance.

**Comment by AnkouOSRS** [comment]
Turns out the event that triggers the timers was broken at the time, the plugin is now working as expected.
